development:
  clients:
    default:
      database: webhook_rails_mongo_heroku_development
      hosts:
        - localhost:27017
      options:
  options:
test:
  clients:
    default:
      database: webhook_rails_mongo_heroku_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
